## *`WHAT IS NUMPY?`*
 - NumPy is an open-source numerical Python library.
 - contains a large number of mathematical, algebraic, and transformation functions
 - Numpy also contains random number generators.
 - Pandas objects rely heavily on NumPy objects.

In [1]:
import numpy as np

In [2]:
np.__version__

'2.1.3'

• Python does numerical computations slowly.
 - 1000 x 1000 matrix multiply
 - Python triple loop takes > 10 min.
 - Numpytakes ~0.03 seconds

_`1D- Numpy Array`_


In [3]:
arr = np.array([10, 20, 30, 40])
arr

array([10, 20, 30, 40])

In [4]:
# Check the Dimension -> Arrays can have any number of dimensions, including zero (a scalar).
arr.ndim

1

In [5]:
# (Rows, Columns)
arr.shape

(4,)

In [6]:
# Print Number of Rows
print(len(arr) == arr.shape[0])
len(arr)

True


4

In [7]:
# How many elements in an array ?
arr.size

4

In [8]:
#  Arrays are dense. Each element of the array exists and has the same type.
arr.dtype

dtype('int64')

_`2D- Numpy Array`_


In [9]:
arr_2d = np.array([[1, 2, 3],
                    [4, 5, 6]])

arr_2d

array([[1, 2, 3],
       [4, 5, 6]])

In [10]:
arr_2d.ndim

2

In [11]:
arr_2d.shape

(2, 3)

In [12]:
len(arr_2d)

2

In [13]:
arr_2d.size

6

In [14]:
# Type of Numpy Array
type(arr_2d)

numpy.ndarray

In [15]:
# Type of Each Element in Numpy Array
arr_2d.dtype

dtype('int64')

- _Every element in the array must be of the same Type and Size_
- _If an array's elements are also arrays, those inner arrays must have the same type and number of elements as each other_


In [16]:
np.array([
    [4.0, 5.0, 6],
    [1, 2]])

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

In [17]:
foo = np.array(['Hello', 1, 2])
foo

array(['Hello', '1', '2'], dtype='<U21')

- _`Cast the Integers to Strings`_
  - U21 : Unicode Strings with 21 Characters or Less


In [18]:
foo[-1] = 'World'
foo

array(['Hello', '1', 'World'], dtype='<U21')

In [19]:
np.array([
    [4.0, 5.0, 6],
    [1, 2, 3]])

array([[4., 5., 6.],
       [1., 2., 3.]])

_`Cast Integers to Float`_


### *`Arrays creation`*
 - np.ones, np.zeros, np.full
 - np.arange
 - np.concatenate
 - np.astype
 - np.zeros_like, np.ones_like
 - np.random.random

_`Numpy Array of Zeros`_


In [20]:
zeros = np.zeros(shape=(4, ))  # 1D Array
zeros

array([0., 0., 0., 0.])

In [21]:
zeros = np.zeros(shape=(4, 5))  # 2D Array
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

_`Numpy Array of Ones`_


In [22]:
ones = np.ones(7)
ones

array([1., 1., 1., 1., 1., 1., 1.])

In [23]:
ones = np.ones((2, 5))
ones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

_`Numpy Array of a Filled Value`_


In [24]:
full = np.full(shape=(3), fill_value=7)
full

array([7, 7, 7])

In [25]:
full = np.full(shape=(3, 4), fill_value=7)
full

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

_`Numpy Array of a Range of Values` 1D Vector_


In [26]:
rng = np.arange(start=4, stop=21, step=2)
rng

array([ 4,  6,  8, 10, 12, 14, 16, 18, 20])

_stop is exclusive and start is inclusive_


In [27]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

_`Numpy Array of a Concatenation of Values`_ -> Join a sequence of arrays along an existing axis.

In [32]:
A = np.ones((3, ))
B = np.zeros((2, ))
print(A)
print(B)

np.concatenate([A, B]) # A & B Must be in the Same Dimension (1D OR 2D OR .....)

[1. 1. 1.]
[0. 0.]


array([1., 1., 1., 0., 0.])

In [ ]:
A = np.ones((3, 4))
B = np.zeros((2, 4))
print(A)
print(B)

# A & B Must be in the Same Dimension (1D OR 2D OR .....) & The same Number of Columns
np.concatenate([A, B], axis=0)      # axis = 0 (Default) -> Place rows under one anthore.

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]


array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
A = np.ones((4, 1))
B = np.zeros((4, 2))
print(A)
print(B)

# A & B Must be in the Same Dimension (1D OR 2D OR .....) & The same Number of Rows
np.concatenate([A, B], axis=1)      # Place Columns beside one anthor

[[1.]
 [1.]
 [1.]
 [1.]]
[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.]])

_`np.astype(DataType)`_ -> Used for changing the type of an array.

In [40]:
A = np.array([10.65, 12.4, 3.14, 50.0])

A.astype(np.int32)

array([10, 12,  3, 50], dtype=int32)

In [41]:
A.astype(str)

array(['10.65', '12.4', '3.14', '50.0'], dtype='<U32')

_`np.full_like, np.zeros_like & np.ones_like`_


In [45]:
A = np.array([[1, 2, 3], [4, 5, 6]])

# Return an array of zeros with the same shape and type as a given array.
np.zeros_like(A)

array([[0, 0, 0],
       [0, 0, 0]])

In [46]:
np.zeros_like(A, dtype=np.float32)

array([[0., 0., 0.],
       [0., 0., 0.]], dtype=float32)

In [47]:
np.full_like(A, fill_value=10, dtype=np.float32)    # Return a full array with the same shape and type as a given array.

array([[10., 10., 10.],
       [10., 10., 10.]], dtype=float32)

In [48]:
# Return a full array with the same shape and type as a given array.
np.ones_like(A, dtype=np.float32)

array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)

_`Random Generators`_


In [49]:
np.random.randint(low=4, high=12)

6

In [50]:
np.random.randint(low=4, high=12, size=(3, 2))

array([[ 6, 10],
       [ 6,  5],
       [ 8,  6]], dtype=int32)

In [51]:
np.random.randint(low=4, high=12, size=(6))

array([ 9,  5, 10,  4,  9, 10], dtype=int32)

In [ ]:
np.random.random((5, 4))    # Generate Float Numbers between 0 & 1 

array([[0.80613415, 0.33463411, 0.2492229 , 0.08166855],
       [0.62388622, 0.18124365, 0.03670392, 0.2076529 ],
       [0.52046582, 0.41768284, 0.4995326 , 0.90119993],
       [0.94610397, 0.57648887, 0.87341401, 0.03298906],
       [0.4204742 , 0.70021066, 0.7100296 , 0.10893892]])

In [ ]:
np.random.randn(2, 4)       # Normal Distribution

array([[-0.66922214, -0.06628822,  0.27286319, -2.47280629],
       [-0.46779387, -1.1770464 ,  2.53964768, -1.56309278]])

- _`Indexing`_
  - _Positive_
  - _Negative_


_You can Create a Numpy Array From List or Tuple_


In [58]:
arr = np.array((10, 20, -10, -23, 10, 23))
arr

array([ 10,  20, -10, -23,  10,  23])

In [59]:
# 1st-element
arr[0]

np.int64(10)

In [60]:
# last element
arr[-1]

np.int64(23)

In [61]:
arr[2]

np.int64(-10)

In [62]:
arr[2] = 100
arr

array([ 10,  20, 100, -23,  10,  23])

In [63]:
arr[10]

IndexError: index 10 is out of bounds for axis 0 with size 6

In [64]:
arr

array([ 10,  20, 100, -23,  10,  23])

_`To Select Multiple Elements by Indexing` [[_ ,_ , _]]_


In [65]:
arr[[0, 1, 4]]

array([10, 20, 10])

_Even if you repeat the index_


In [66]:
arr[[0, 1, 4, 0]] 

array([10, 20, 10, 10])

In [67]:
np.zeros(shape=3)  # Default : Float

array([0., 0., 0.])

In [68]:
np.zeros(shape=3, dtype=int)

array([0, 0, 0])

In [69]:
arr[np.zeros(shape=3, dtype=int)]

array([10, 10, 10])

_Same Thing with ones and full_


In [70]:
np.ones(shape=(3))

array([1., 1., 1.])

In [71]:
np.ones(shape=(3), dtype=int)

array([1, 1, 1])

In [72]:
arr[np.ones(shape=(3), dtype=int)]

array([20, 20, 20])

In [73]:
np.full(shape=(3), fill_value=2)  # Defult : Integer

array([2, 2, 2])

In [74]:
np.full(shape=(3), fill_value=2, dtype=float)

array([2., 2., 2.])

In [75]:
arr[np.full(shape=(3), fill_value=2)]

array([100, 100, 100])

_`Slicing: ` [Start: End: Step]_


In [76]:
arr[2:5:2]

array([100,  10])

In [77]:
arr[::3]  # Start = 0 and End= Length - 1 (Default)

array([ 10, -23])

In [78]:
arr[:4]  # Step = 1 (Default)

array([ 10,  20, 100, -23])

_Tricky_


In [79]:
arr[[0, 1, 2]] = [-20, 12, 19]
arr

array([-20,  12,  19, -23,  10,  23])

In [80]:
arr[[0, 1, 0]] = [1, 2, 3]  # Even if it is repeated
arr

array([  3,   2,  19, -23,  10,  23])

_`Indexing & Slicing on Multidimensional Array` [Row, Column]_


In [81]:
arr = np.array([[1, 2, 3],
                [7, 8, 9],
                [-1, 2, 10]])
arr

array([[ 1,  2,  3],
       [ 7,  8,  9],
       [-1,  2, 10]])

In [82]:
arr[0]  # Row 0

array([1, 2, 3])

In [83]:
arr[1]  # Row 1

array([7, 8, 9])

In [84]:
arr[2]  # Row 2

array([-1,  2, 10])

In [85]:
arr[:, 0]  # All Rows and Column 0

array([ 1,  7, -1])

In [86]:
arr[:, 1]  # All Rows and Column 1

array([2, 8, 2])

In [87]:
arr[:, 2]  # All Rows and Column 2

array([ 3,  9, 10])

In [88]:
arr[:, :]  # All Array Values

array([[ 1,  2,  3],
       [ 7,  8,  9],
       [-1,  2, 10]])

In [89]:
arr[1:, 0:2]

array([[ 7,  8],
       [-1,  2]])

In [90]:
arr[1:, 0:2] = [[1, 2], [3, 4]]

arr

array([[ 1,  2,  3],
       [ 1,  2,  9],
       [ 3,  4, 10]])

In [91]:
# (0, 0) & (1, 1) & (2, 2) -> Diagnoal Part
arr[[0, 1, 2], [0, 1, 2]] = [10, 20, 30]
arr

array([[10,  2,  3],
       [ 1, 20,  9],
       [ 3,  4, 30]])

In [92]:
arr[0, 1] = 20
arr

array([[10, 20,  3],
       [ 1, 20,  9],
       [ 3,  4, 30]])

### *`Shaping`* 
 1. Total number of elements cannot change.
 2. Use -1 to infer axis shape
 3. Row-major by default (MATLAB is column-major)

In [93]:
a = np.array([1,2,3,4,5,6])
a

array([1, 2, 3, 4, 5, 6])

In [94]:
a.size

6

In [95]:
a.reshape(2, 3)

array([[1, 2, 3],
       [4, 5, 6]])

In [96]:
a.reshape(3, 2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [97]:
a.reshape(1, 6)

array([[1, 2, 3, 4, 5, 6]])

In [98]:
a.reshape(6, 1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

*`The size must be the same of the original array size`*

In [99]:
a.reshape(2, -1)

array([[1, 2, 3],
       [4, 5, 6]])

*` -1 : Means with the Row = 2, Find the Appropriate number of Columns`*

In [101]:
a.reshape(-1, 2)

array([[1, 2],
       [3, 4],
       [5, 6]])

*` -1 : Means with the Column = 2, Find the Appropriate number of Rows`*

*`Convert any Dimension to 1D Vector`*

In [104]:
a.ravel()

array([1, 2, 3, 4, 5, 6])

In [105]:
a.flatten()

array([1, 2, 3, 4, 5, 6])

### *`Views & Copies`*
 - Views share data with the original array, like references in Java/C++. Altering entries of a view, changes the same entries in the original.
 - np.copy, np.view make explicit copies and views.

In [125]:
A = np.array([[1, 2, 3],
                [4, 5, 6]], dtype=float)
A

array([[1., 2., 3.],
       [4., 5., 6.]])

In [126]:
B = np.copy(A)      # Doesnot affect the original.
print(B)

B[0][0] = 22
print(B)
print(A)

[[1. 2. 3.]
 [4. 5. 6.]]
[[22.  2.  3.]
 [ 4.  5.  6.]]
[[1. 2. 3.]
 [4. 5. 6.]]


In [127]:
B = A.view()      # Affect the original.
print(B)

B[0][0] = 22
print(B)
print(A)

[[1. 2. 3.]
 [4. 5. 6.]]
[[22.  2.  3.]
 [ 4.  5.  6.]]
[[22.  2.  3.]
 [ 4.  5.  6.]]


### *`Transposition`*
- np.transpose permutes axes.
- a.T transposes the first two axes.

In [128]:
A

array([[22.,  2.,  3.],
       [ 4.,  5.,  6.]])

In [129]:
a = A.T
print(a)

a = A.transpose((1,0))
print(a)

[[22.  4.]
 [ 2.  5.]
 [ 3.  6.]]
[[22.  4.]
 [ 2.  5.]
 [ 3.  6.]]


_`Math Operations on Arrays`_


In [106]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

_Element-Wise Operation_


In [107]:
arr1 + arr2

array([[ 6,  8],
       [10, 12]])

In [108]:
arr2 - arr1

array([[4, 4],
       [4, 4]])

In [109]:
arr1 * arr2

array([[ 5, 12],
       [21, 32]])

In [110]:
arr2 / arr1

array([[5.        , 3.        ],
       [2.33333333, 2.        ]])

In [111]:
# Matrix Multiplication
arr1 @ arr2

array([[19, 22],
       [43, 50]])

In [112]:
arr1.dot(arr2)

array([[19, 22],
       [43, 50]])

_`Challenge 1` With your high school reunion fast approaching, you decide to get in shape and lose some weight. You record you weight every day for five weeks starting on Monday. Given these daily weights, build an array with your average weight per weekend_


In [113]:
daily_weight = 185 - np.arange(5*7) / 5
daily_weight

array([185. , 184.8, 184.6, 184.4, 184.2, 184. , 183.8, 183.6, 183.4,
       183.2, 183. , 182.8, 182.6, 182.4, 182.2, 182. , 181.8, 181.6,
       181.4, 181.2, 181. , 180.8, 180.6, 180.4, 180.2, 180. , 179.8,
       179.6, 179.4, 179.2, 179. , 178.8, 178.6, 178.4, 178.2])

In [114]:
len(daily_weight)

35

In [117]:
# weeks
week1 = daily_weight[0:7]
week2 = daily_weight[7:14]
week3 = daily_weight[14:21]
week4 = daily_weight[21:28]
week5 = daily_weight[28:35]


weeks = [week1, week2, week3, week4, week5]
averages = []
for week in weeks:
    avg = sum(week) / len(week)
    averages.append(avg)

averages = np.array(averages)
averages

array([184.4, 183. , 181.6, 180.2, 178.8])

In [168]:
weekends = daily_weight[5::7]
sundays = daily_weight[6::7]

weekend_avg = (weekends + sundays) / 2
weekend_avg

array([183.9, 182.5, 181.1, 179.7, 178.3])

30:00
